version: "3"
services:

  app:
    container_name: express_app
    build:
      context: ./app

    ports:
      - "3000:3000"
      
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/messages || exit 1"]
      interval: 30s
      timeout: 30s
      retries: 3